services:
    ger.modbreak.listener:
        class: ger\modbreak\event\main_listener
        arguments:
            - '@auth'
            - '@request'
        tags:
            - { name: event.listener }
